export {
  MONTH_DEFAULT,
  YEAR_DEFAULT,
  CVC_DEFAULT,
  CARD_NUMBER_DEFAULT,
  CARD_HOLDER_NAME_DEFAULT,
}

const MONTH_DEFAULT = "00"
const YEAR_DEFAULT = "00"
const CVC_DEFAULT = "000"
const CARD_NUMBER_DEFAULT = "0000000000000000"
const CARD_HOLDER_NAME_DEFAULT = "-------- --------"
